version: '3'

services:

  app:
    container_name: docker-node-mysql
    build: .
    ports:
      - "8080:3000"
    links:
      - mysql-dev
    depends_on:
      - mysql-dev
    restart: always
    command: npm start
    volumes:
      - ".:/usr/src/app"

  mysql-dev:
    container_name: mysql-container
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_crud
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80

volumes:
  mysql_data:
